# Generated by Django 4.2.9 on 2024-01-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbed',
            old_name='user',
            new_name='testbed_uploader',
        ),
    ]
