# Generated by Django 4.2.9 on 2024-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbeds', '0002_rename_user_testbed_testbed_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='notes',
            field=models.TextField(default='Add Notes'),
        ),
        migrations.AlterField(
            model_name='testbed',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
