# Generated by Django 4.2.9 on 2024-01-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbeds', '0004_alter_testbed_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='usage',
            field=models.TextField(default='notfree'),
        ),
        migrations.AlterField(
            model_name='testbed',
            name='location',
            field=models.TextField(),
        ),
    ]
