# Generated by Django 4.2.9 on 2024-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbeds', '0005_testbed_usage_alter_testbed_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='device_type',
            field=models.TextField(default='FTD'),
        ),
    ]
