# Generated by Django 4.2.9 on 2024-01-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
