# Generated by Django 4.2.9 on 2024-01-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_testbedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestbedPost',
        ),
    ]
